-- CreateEnum
CREATE TYPE "RoomStatus" AS ENUM ('CLEAN', 'DIRTY', 'OUT_OF_ORDER', 'OUT_OF_SERVICE');

-- AlterEnum
ALTER TYPE "BookingStatus" ADD VALUE 'NO_SHOW';

-- AlterTable
ALTER TABLE "PosOrderItem" ALTER COLUMN "itemName" DROP NOT NULL;

-- Safe rename for RoomType string
ALTER TABLE "Room" RENAME COLUMN "roomType" TO "legacyType";

-- AlterTable Room
ALTER TABLE "Room" ADD COLUMN     "roomTypeId" TEXT,
ADD COLUMN     "status" "RoomStatus" NOT NULL DEFAULT 'CLEAN';

-- CreateTable
CREATE TABLE "PropertySettings" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "propertyName" TEXT NOT NULL,
    "legalName" TEXT,
    "address" TEXT,
    "city" TEXT,
    "state" TEXT,
    "pinCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'India',
    "phone" TEXT,
    "email" TEXT,
    "gstin" TEXT,
    "checkInTime" TEXT NOT NULL DEFAULT '14:00',
    "checkOutTime" TEXT NOT NULL DEFAULT '11:00',
    "invoicePrefix" TEXT NOT NULL DEFAULT 'INV-',
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PropertySettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoomType" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "baseOccupancy" INTEGER NOT NULL DEFAULT 2,
    "maxAdults" INTEGER NOT NULL DEFAULT 3,
    "maxChildren" INTEGER NOT NULL DEFAULT 2,
    "baseRate" DECIMAL(10,2) NOT NULL,
    "extraAdultRate" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "extraChildRate" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RoomType_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PropertySettings_tenantId_key" ON "PropertySettings"("tenantId");

-- CreateIndex
CREATE INDEX "RoomType_tenantId_idx" ON "RoomType"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "RoomType_tenantId_name_key" ON "RoomType"("tenantId", "name");

-- CreateIndex
CREATE INDEX "Room_tenantId_idx" ON "Room"("tenantId");

-- AddForeignKey
ALTER TABLE "Room" ADD CONSTRAINT "Room_roomTypeId_fkey" FOREIGN KEY ("roomTypeId") REFERENCES "RoomType"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PropertySettings" ADD CONSTRAINT "PropertySettings_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoomType" ADD CONSTRAINT "RoomType_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- BACKFILL ROOM TYPE
-- Create default room types based on legacy types
INSERT INTO "RoomType" ("id", "tenantId", "name", "description", "baseOccupancy", "maxAdults", "maxChildren", "baseRate", "extraAdultRate", "extraChildRate", "isActive", "createdAt", "updatedAt")
SELECT 
    gen_random_uuid(), 
    "tenantId", 
    COALESCE("legacyType", 'Standard'), 
    'Autogenerated from legacy room type', 
    2, 3, 2, MAX("baseRate"), 0, 0, true, NOW(), NOW()
FROM "Room"
GROUP BY "tenantId", "legacyType"
ON CONFLICT DO NOTHING;

-- Link rooms to room types
UPDATE "Room" r
SET "roomTypeId" = (
    SELECT rt."id" FROM "RoomType" rt 
    WHERE rt."tenantId" = r."tenantId" AND rt."name" = COALESCE(r."legacyType", 'Standard')
    LIMIT 1
);

-- Optional: Verify that all rooms have a room type
DO $DO$
BEGIN
  IF EXISTS (SELECT 1 FROM "Room" WHERE "roomTypeId" IS NULL) THEN
    RAISE EXCEPTION 'Backfill failed: Some Rooms still have NULL roomTypeId';
  END IF;
END
$DO$;
